apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: unmanaged
  annotations:
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: managed
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
